title: Digitally Enlightened
description: Stateless observations of transient digital world
author: vayudoot
github: https://github.com/vayudoot
about: A technophile with wide ranging interests.
avatar_url: /static/img/avatar.jpg
timezone: GMT
highlighter: rouge
google_analytics: 

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-github
      link: "https://github.com/vayudoot"

share:
  twitter_username: 

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml
    - text: Sitemap
      url: /sitemap.xml

url: "https://vayudoot.org"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
